### ISSUE TITLE
gwa --version returns "x Error Unable to verify you have the latest version"

### ISSUE THREAD

**Issue by dkelsey** [bcgov/gwa-cli#29] opened 2021-05-27 22:54 UTC
When I run
```bash
[app@alkaid:~]> ./gwa --version
x Error Unable to verify you have the latest version
```

This is a fresh download of the `gwa` client `gwa_v1.1.4_linux_x64.zip`

On another host:
```bash
[app@megrez:~]> gwa --version
1.1.4
```

**Comment by dkelsey** [comment] 2021-05-27 23:23
The error seems to come an go?
In the same ssh session I got the expected result:
```bash
[app@alkaid:~]> gwa --version
1.1.4
[app@alkaid:~]> gwa --version
1.1.4
[app@alkaid:~]> gwa info
x Error Fetchrequest to https://authz-apps-gov-bc-ca..api.gov.bc.ca/auth/realms/aps/protocol/openid-connect/token failed, reason: getaddrinfo ENOTFOUND authz-apps-gov-bc-ca..api.gov.bc.ca
[app@alkaid:~]> gwa info
x Error Fetchrequest to https://authz-apps-gov-bc-ca..api.gov.bc.ca/auth/realms/aps/protocol/openid-connect/token failed, reason: getaddrinfo ENOTFOUND authz-apps-gov-bc-ca..api.gov.bc.ca
[app@alkaid:~]> gwa --version
x Error Unable to verify you have the latest version
```

**Comment by dkelsey** [comment] 2021-05-28 00:16
```bash
[app@alkaid:~]> while (:); do gwa --version ; done
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
1.1.4
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
x Error Unable to verify you have the latest version
...
```

**Comment by Jonesy** [comment] 2021-05-28 14:51
It might be rate limiting on Github's API that is causing this, I recall it not being incredibly forgiving. We might have to look into caching the current version somewhere. For the 1.2 release I will slacken the rules so the command won't terminate if it can't reach GitHub. Hope to release today.

**Comment by dkelsey** [comment] 2021-05-28 15:05
Thing is, the call appears to work without any issue on another host.

**Comment by Jonesy** [comment] 2021-05-28 22:49
I feel like this might be a network issue based on the narrow location of the cause, but I made adjustments to the commands so for simple outputs like that we won't be doing a round the world check for API and CLI versions, they'll just output the goods you need. Once 1.2 ships I'll close this, but if you keep seeing weird behaviour reopen and I'll investigate more!

**Comment by dkelsey** [comment] 2021-06-01 19:47
I noticed that the associated github actions used `1.1.2`.
I downloaded it and rant this and ran this:

```bash
while (:); do echo "run: 1.1.2"; ./gwa --version ; echo "run: 1.1.4"; ./gwa.1.1.4 --version ; echo ; done
run: 1.1.2
1.1.2
run: 1.1.4
x Error Unable to verify you have the latest version

run: 1.1.2
1.1.2
run: 1.1.4
x Error Unable to verify you have the latest version

run: 1.1.2
1.1.2
run: 1.1.4
x Error Unable to verify you have the latest version

run: 1.1.2
1.1.2
run: 1.1.4
x Error Unable to verify you have the latest version

run: 1.1.2
1.1.2
run: 1.1.4
x Error Unable to verify you have the latest version
```

**Comment by dkelsey** [comment] 2021-06-01 22:37
I've reverted to the 1.1.2 version of the client for now.

**Comment by Jonesy** [comment] 2021-06-02 04:17
K, I'll ping you when 1.2 is out for testing, I am pretty sure it'll allow you to use it without an API check killing the process. There will be some better error reporting next sprint with 1.2.1.

**Comment by Jonesy** [comment] 2021-06-02 17:50
1.2.0 has been released, `version` and `info` commands will not try to run any remote verification. For the other commands it'll throw an error instead of printing an incorrect error message.

**Closed by Jonesy** 2021-06-02 17:50 UTC
